version: '3'

services:
  web:
    container_name: referhub-web
    image: nginx
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./var/log:/var/log/nginx

  php: &php
    build:
      context: .
      dockerfile: Dockerfile
    #environment:
    #  - APP_ENV=dev
    #  - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app:rw,cached
      - /app/var
    depends_on:
      - redis

  referhub-php:
    <<: *php
    container_name: referhub-php

  redis:
    container_name: referhub-redis
    image: redis
    ports:
      - 63798:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  database:
    container_name: referhub-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRESDB: referhub
    ports:
      - 15432:5432
    volumes:
      - ./docker/db/db_data:/var/lib/postgresql/data

